### ISSUE TITLE
Error loading project locally

### ISSUE THREAD

**Issue by Krashcan** [Visrozar/PiratesInDungeon#1]
I get the following error 
`Broken YAML file(Assets/Animation/Player.controller). Local file identifier (1107481668941021040) doesn't exist!
UnityEditor.DockArea:OnGUI()`

I have Unity5 32bit. Also, I can see a lot of warnings. I couldn't makeout anything out of them. Also, in the hierarchy, it says missing prefabs.

![screenshot 137](https://cloud.githubusercontent.com/assets/18661082/23940902/a85303e6-098c-11e7-95f2-de62f4b2c43d.png)

**Comment by Visrozar** [comment]
The YAML file should contain a reference to a file. m_DstState: {fileID: 1107481668941021040}. You can delete the file or delete the references and it should build automatically.

BTW, I sincerely suggest to use 64 bit instead.

**Comment by Krashcan** [comment]
Ok, I will upgrade it to 64bit.

**Comment by Krashcan** [comment]
Removing `    m_StateMachine: {fileID: 1107481668941021040}
` from line no. 44 in Assets/Animation/Player.controller fixed the problem
